# Generated by Django 5.1.4 on 2024-12-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='objet_cible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
