# Generated by Django 5.1.4 on 2025-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='account/photos/', verbose_name='photo'),
        ),
    ]
