# Generated by Django 5.1.4 on 2025-07-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_base', '0001_initial'),
        ('account', '0005_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_base.juridictions'),
        ),
    ]
