# Generated by Django 5.1.4 on 2025-09-26 12:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFile', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('originalName', models.TextField(verbose_name='nom original')),
                ('path', models.TextField(verbose_name='path')),
            ],
        ),
        migrations.CreateModel(
            name='Juridictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJuridiction', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('name', models.TextField(verbose_name='juridiction')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='privilege')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='telephone')),
                ('typeTribunal', models.CharField(blank=True, max_length=200, null=True, verbose_name='type de tribunal')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
