# Generated by Django 5.1.4 on 2025-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageDefilant',
        ),
    ]
