# Generated by Django 5.1.4 on 2025-10-09 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaireroles',
            name='appelants',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='civileResponsables',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='detention',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='intimes',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='mandatDepot',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='natureInfraction',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='partieCiviles',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='affaireroles',
            name='prevenus',
        ),
        migrations.CreateModel(
            name='AffaireAttentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAffaire', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numOrdre', models.IntegerField(verbose_name="Numéro d'ordre")),
                ('numRg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Rg')),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire')),
                ('objet', models.TextField(blank=True, null=True, verbose_name='Objet')),
                ('demandeurs', models.TextField(blank=True, null=True, verbose_name='Demandeurs')),
                ('defendeurs', models.TextField(blank=True, null=True, verbose_name='Défendeurs')),
                ('statut', models.TextField(blank=True, choices=[('Pending', 'En attente'), ('Start', 'Repris')], default='Creer', null=True, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date creation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creer par')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.roles', verbose_name='Role')),
            ],
        ),
    ]
