# Generated by Django 5.1.4 on 2025-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisions',
            name='extrait',
        ),
        migrations.AddField(
            model_name='decisions',
            name='dispositif',
            field=models.TextField(blank=True, null=True, verbose_name='Dispositif'),
        ),
    ]
