# Generated by Django 5.1.4 on 2025-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_remove_decisions_extrait_decisions_dispositif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisions',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True, verbose_name='Type decision'),
        ),
    ]
