# Generated by Django 5.1.4 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_affaireattentes_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionhistory',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Vide-du-delibere-exeption', 'Vidé du exeception forme'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Renvoi-chambre-conseil', 'Renvoi en chambre du conseil'), ('Surcie-statuer', 'Surcie à statuer'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Vide-du-delibere-exeption', 'Vidé du exeception forme'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Renvoi-chambre-conseil', 'Renvoi en chambre du conseil'), ('Surcie-statuer', 'Surcie à statuer'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True, verbose_name='Type decision'),
        ),
    ]
