# Generated by Django 5.1.4 on 2025-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_decisions_typedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollement',
            name='motifAnnulation',
            field=models.TextField(blank=True, null=True, verbose_name='Motif annulation'),
        ),
    ]
