# Generated by Django 5.1.4 on 2025-10-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_decisionhistory_typedecision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaireattentes',
            name='role',
        ),
        migrations.AddField(
            model_name='affaireattentes',
            name='roleProvenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaires_provenance', to='role.roles', verbose_name='Role provenance'),
        ),
        migrations.AddField(
            model_name='affaireattentes',
            name='roleReprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaires_reprise', to='role.roles', verbose_name='Role reprise'),
        ),
    ]
