# Generated by Django 5.1.4 on 2025-08-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_base', '0002_delete_messagedefilant'),
        ('role', '0004_enrollement_motifannulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollement',
            name='appelants',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='civileResponsables',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='detention',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='intimes',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='mandatDepot',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='natureInfraction',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='partieCiviles',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='prevenus',
        ),
        migrations.CreateModel(
            name='EnrollementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOrdre', models.IntegerField()),
                ('numRg', models.CharField(blank=True, max_length=200, null=True)),
                ('numAffaire', models.CharField(blank=True, max_length=200, null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('demandeurs', models.TextField(blank=True, null=True)),
                ('defendeurs', models.TextField(blank=True, null=True)),
                ('dateEnrollement', models.DateField(blank=True, null=True)),
                ('dateAudience', models.DateField(blank=True, null=True)),
                ('typeAudience', models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Refere', 'Référé'), ('Fond', 'Fond'), ('Civile', 'Civile'), ('Correctionnelle', 'Correctionnelle'), ('Criminelle', 'Criminelle')], null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('statut', models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True)),
                ('motifAnnulation', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_base.juridictions')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='role.enrollement')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
