# Generated by Django 5.1.4 on 2025-08-13 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_base', '0002_delete_messagedefilant'),
        ('role', '0005_remove_enrollement_appelants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, choices=[('Premiere-Section', 'Prémière Section'), ('Deuxieme-Section', 'Deuxième Section'), ('Troisieme-Section', 'Troisième Section'), ('Quatrieme-Section', 'Quatrième Section'), ('Cinquieme-Section', 'Cinquième Section'), ('Section-Presidentielle', 'Section Présidentielle')], null=True)),
                ('typeDecision', models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('president', models.TextField(blank=True, null=True)),
                ('greffier', models.TextField(blank=True, null=True)),
                ('dateDecision', models.DateField(blank=True, null=True)),
                ('dispositif', models.TextField(blank=True, null=True)),
                ('prochaineAudience', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.affaireroles')),
                ('juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_base.juridictions')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='role.decisions')),
            ],
        ),
    ]
