# Generated by Django 5.1.4 on 2025-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_decisionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisions',
            name='statut',
            field=models.TextField(blank=True, choices=[('Creer', 'Créée'), ('Modifier', 'Modifiée'), ('Annuler', 'Annulée')], default='Creer', null=True, verbose_name='Statut'),
        ),
    ]
