# Generated by Django 5.1.4 on 2025-08-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_decisions_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='statut',
            field=models.TextField(blank=True, choices=[('En-attente', 'En attente'), ('Valider', 'Validé')], default='En-attente', null=True, verbose_name='Statut'),
        ),
    ]
