# Generated by Django 5.1.4 on 2025-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_alter_decisionhistory_typedecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionhistory',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Renvoi-chambre-conseil', 'Renvoi en chambre de conseil'), ('Sursis-statuer', 'Sursis à statuer'), ('Mise-en-etat', 'Mise en état'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='typeDecision',
            field=models.TextField(blank=True, choices=[('Renvoi', 'Renvoi'), ('Mise-en-delibere', 'Mise en délibéré'), ('Vide-du-delibere', 'Vidé du délibéré'), ('Delibere-proroge', 'Délibéré prorogé'), ('Radiation', 'Radiation'), ('Renvoi-sine-die', 'Renvoi sine die'), ('Renvoi-chambre-conseil', 'Renvoi en chambre de conseil'), ('Sursis-statuer', 'Sursis à statuer'), ('Mise-en-etat', 'Mise en état'), ('Affectation', 'Affectation'), ('Autre', 'Autre')], null=True, verbose_name='Type decision'),
        ),
    ]
