# Generated by Django 5.1.4 on 2025-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_roles_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionhistory',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='numAffaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro Affaire'),
        ),
    ]
