# Generated by Django 5.1.4 on 2024-12-12 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRccm', models.TextField(blank=True, choices=[('PersonnePhysique', 'Personne physique'), ('Personne_morale', 'Personne morale')], null=True, verbose_name='Type Rccm')),
                ('numeroFormalite', models.TextField(blank=True, null=True, verbose_name='Numéro Formalite')),
                ('denomination', models.TextField(blank=True, null=True, verbose_name='Denomination')),
                ('siegeSocial', models.TextField(blank=True, null=True, verbose_name='Siege Social')),
                ('typeFormalite', models.TextField(blank=True, choices=[('Modification', 'Modification'), ('Radiation', 'Radiation'), ('Dissolution', 'Dissolution')], null=True, verbose_name='Type Formalité')),
                ('declarationModificative', models.TextField(blank=True, choices=[('Activite', 'Activite'), ('Denomination', 'Denomination'), ('Siege_social', 'Siege Social')], null=True, verbose_name='Déclaration modificative')),
                ('dateModification', models.DateField(blank=True, null=True, verbose_name='Date Modification')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation formalité')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Formalité Creer par')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementSecondaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('rccm', models.TextField(blank=True, null=True, verbose_name='N')),
                ('activites', models.TextField(blank=True, null=True, verbose_name='Activités')),
                ('activitesAjouter', models.TextField(blank=True, null=True, verbose_name='Activités Ajoutées')),
                ('activitesSupprimer', models.TextField(blank=True, null=True, verbose_name='Activités Supprimées')),
                ('activitesActualiser', models.TextField(blank=True, null=True, verbose_name='Activités Actualisées')),
                ('autresActivites', models.TextField(blank=True, null=True, verbose_name='Autres Activités')),
                ('adresseEtablissement', models.TextField(blank=True, null=True, verbose_name='Adresse etablissement')),
                ('ancienneAdresse', models.TextField(blank=True, null=True, verbose_name='Ancienne adresse')),
                ('nouvelleAdresse', models.TextField(blank=True, null=True, verbose_name='Nouvelle adresse')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation etablissement secondaire')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('rccm', models.TextField(blank=True, null=True, verbose_name='N')),
                ('activites', models.TextField(blank=True, null=True, verbose_name='Activités')),
                ('activitesAjouter', models.TextField(blank=True, null=True, verbose_name='Activités Ajoutées')),
                ('activitesSupprimer', models.TextField(blank=True, null=True, verbose_name='Activités Supprimées')),
                ('activitesActualiser', models.TextField(blank=True, null=True, verbose_name='Activités Actualisées')),
                ('adresseEtablissement', models.TextField(blank=True, null=True, verbose_name='Adresse etablissement')),
                ('ancienneAdresse', models.TextField(blank=True, null=True, verbose_name='Ancienne adresse')),
                ('nouvelleAdresse', models.TextField(blank=True, null=True, verbose_name='Nouvelle adresse')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation etablissement')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreCivil', models.TextField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], null=True, verbose_name='Titre civil')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('typeDemande', models.TextField(blank=True, choices=[('Une_demande_de_modification_de_la_personne_physique_et_ou_de_son_etablissement_principale', 'Une demande de modification de la personne physique et ou de son etablissement principale'), ('Une demande_de_modification_dun_etablissement_secondaire_ou_une_succursale', "Une demande de modification d'un etablissement secondaire ou une succursale")], null=True, verbose_name='Demande')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation gerant')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreCivil', models.TextField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], null=True, verbose_name='Titre civil')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naisssance')),
                ('nationnalite', models.TextField(blank=True, null=True, verbose_name='Nationnalité')),
                ('adressePostale', models.TextField(blank=True, null=True, verbose_name='Adresse postale')),
                ('telephone', models.TextField(blank=True, null=True, verbose_name='Telephone')),
                ('domicile', models.TextField(blank=True, null=True, verbose_name='Domicile personnel')),
                ('ville', models.TextField(blank=True, null=True, verbose_name='Ville')),
                ('quartier', models.TextField(blank=True, null=True, verbose_name='Quartier')),
                ('autrePrecision', models.TextField(blank=True, null=True, verbose_name='Autres precisions')),
                ('coordonneesElectro', models.TextField(blank=True, null=True, verbose_name='Coordonnées electroniques')),
                ('situationMatrimoniale', models.TextField(blank=True, choices=[('Celibataire', 'Célibataire'), ('Marie(e)', 'Marié(e)'), ('Veuf(e)', 'Veuf(e)'), ('Divorce(e)', 'Divorcé(e)')], null=True, verbose_name='Situation matrimonial')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation personne physique')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnePhysiqueEngager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naisssance')),
                ('nationnalite', models.TextField(blank=True, null=True, verbose_name='Nationnalité')),
                ('domicile', models.TextField(blank=True, null=True, verbose_name='Domicile personnel')),
                ('modeDomicilier', models.TextField(blank=True, choices=[('Partante', 'Partante'), ('Nouvelle', 'Nouvelle'), ('En_place', 'En place')], null=True, verbose_name='Mode domicilier')),
                ('objetModification', models.TextField(blank=True, null=True, verbose_name='Objet Modification')),
                ('dateModification', models.DateField(blank=True, null=True, verbose_name='Date modification')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation personne engager')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='Rccm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRccm', models.TextField(blank=True, null=True, verbose_name='Numéro Rccm')),
                ('dateEnreg', models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement")),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation Rccm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rccm Creer par')),
            ],
        ),
        migrations.AddField(
            model_name='formalite',
            name='rccm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.rccm', verbose_name='Rccm'),
        ),
        migrations.CreateModel(
            name='Tableau_personne_physique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjoint', models.TextField(blank=True, null=True, verbose_name='Conjoint')),
                ('nomComplet', models.TextField(blank=True, null=True, verbose_name='Nom et prenom')),
                ('dateLieuMariage', models.TextField(blank=True, null=True, verbose_name='Date et lieu de mariage')),
                ('optionMatrimoniale', models.TextField(blank=True, null=True, verbose_name='Option matrimoniale')),
                ('regimeMatrimoniale', models.TextField(blank=True, null=True, verbose_name='Regime matrimoniale')),
                ('demandeSeparationBien', models.TextField(blank=True, null=True, verbose_name='Demande en séparation de biens')),
                ('personnePhysique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.personnephysique', verbose_name='personne physique')),
            ],
        ),
    ]
