# Generated by Django 5.1.4 on 2024-12-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tableau_personne_physique',
            new_name='Foyer_personne_physique',
        ),
    ]
