# Generated by Django 5.1.4 on 2024-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0002_rename_tableau_personne_physique_foyer_personne_physique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnephysique',
            name='nomCommercial',
        ),
        migrations.RemoveField(
            model_name='personnephysique',
            name='sigle',
        ),
        migrations.AddField(
            model_name='formalite',
            name='nomCommercial',
            field=models.TextField(blank=True, null=True, verbose_name='Nom commercial'),
        ),
        migrations.AddField(
            model_name='formalite',
            name='sigle',
            field=models.TextField(blank=True, null=True, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='declarationModificative',
            field=models.TextField(blank=True, choices=[('Activite', "L'activite"), ('Denomination', 'La dénomination'), ('Siege_social', 'Au siège Social')], null=True, verbose_name='Déclaration modificative'),
        ),
    ]
