# Generated by Django 5.1.4 on 2024-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0003_remove_personnephysique_nomcommercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='optionActivite',
            field=models.TextField(blank=True, choices=[('Rajout', 'Rajout'), ('Suppression', 'Suppression'), ('Suppression_et_Rajout', 'Suppression et Rajout'), ('Changement', 'Changement')], null=True, verbose_name='Option activite'),
        ),
    ]
