# Generated by Django 5.1.4 on 2024-12-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0004_formalite_optionactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='mandataire',
            field=models.TextField(blank=True, null=True, verbose_name='Mandataire'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='declarationModificative',
            field=models.TextField(blank=True, choices=[("A L'ACTIVITE", "L'activite"), ('A LA DENOMINATION', 'La dénomination'), ('AU SIEGE SOCIAL', 'Au siège Social')], null=True, verbose_name='Déclaration modificative'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='typeRccm',
            field=models.TextField(blank=True, choices=[('PERSONNE PHYSIQUE', 'Personne physique'), ('PERSONNE MORALE', 'Personne morale')], null=True, verbose_name='Type Rccm'),
        ),
    ]
