# Generated by Django 5.1.4 on 2025-01-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0005_formalite_mandataire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnephysiqueengager',
            old_name='dateModification',
            new_name='dateModification2',
        ),
    ]
