# Generated by Django 5.1.4 on 2025-01-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0006_rename_datemodification_personnephysiqueengager_datemodification2'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer_personne_physique',
            name='formalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité'),
        ),
    ]
