# Generated by Django 5.1.4 on 2025-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0007_foyer_personne_physique_formalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rccm',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social'),
        ),
        migrations.AddField(
            model_name='rccm',
            name='duree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (en années)'),
        ),
        migrations.AddField(
            model_name='rccm',
            name='forme_juridique',
            field=models.CharField(default='SARL', max_length=50, verbose_name='Forme Juridique'),
        ),
        migrations.AddField(
            model_name='rccm',
            name='nom_banque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la Banque'),
        ),
        migrations.AddField(
            model_name='rccm',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de Compte'),
        ),
    ]
