# Generated by Django 5.1.4 on 2025-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0008_rccm_capital_social_rccm_duree_rccm_forme_juridique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteAnterieure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite_precedente', models.BooleanField(default=False, verbose_name="Exercice d'une précédente activité")),
                ('type_activite', models.CharField(blank=True, choices=[('commercial', 'Commerciale'), ('other', 'Autre')], max_length=20, null=True, verbose_name="Nature de l'activité")),
                ('details_autre_activite', models.CharField(blank=True, max_length=255, null=True, verbose_name="Détails sur l'autre activité")),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin (mois et année)')),
                ('rccm_precedent', models.CharField(blank=True, max_length=100, null=True, verbose_name="Précédent RCCM (s'il y a lieu)")),
                ('etablissement_principal', models.TextField(blank=True, null=True, verbose_name='Établissement principal')),
                ('etablissements_secondaires', models.TextField(blank=True, null=True, verbose_name='Établissements secondaires')),
                ('rccm_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name="RCCM principal (s'il y a lieu)")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse géographique et postale')),
            ],
            options={
                'verbose_name': 'Activité antérieure',
                'verbose_name_plural': 'Activités antérieures',
            },
        ),
    ]
