# Generated by Django 5.1.4 on 2025-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0009_activiteanterieure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rccm',
            name='forme_juridique',
            field=models.CharField(blank=True, default='SARL', max_length=50, null=True, verbose_name='Forme Juridique'),
        ),
    ]
