# Generated by Django 5.1.4 on 2025-01-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0011_rccm_rccm_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rccm',
            name='rccm_file',
        ),
    ]
