# Generated by Django 5.1.4 on 2025-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0012_remove_rccm_rccm_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rccm',
            name='rccm_file',
            field=models.FileField(blank=True, null=True, upload_to='rccm_files/', verbose_name='Fichier associé'),
        ),
    ]
