# Generated by Django 5.1.4 on 2025-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0013_rccm_rccm_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='FormaliteSignee',
            field=models.FileField(blank=True, null=True, upload_to='formalite_signees/', verbose_name='Formalité signée'),
        ),
    ]
