# Generated by Django 5.1.4 on 2025-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0014_formalite_formalitesignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formalite',
            old_name='FormaliteSignee',
            new_name='formaliteSignee',
        ),
    ]
