# Generated by Django 5.1.4 on 2025-04-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0015_rename_formalitesignee_formalite_formalitesignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='declarationModificative',
        ),
        migrations.CreateModel(
            name='OptionDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='rccm.declaration')),
            ],
        ),
        migrations.AddField(
            model_name='formalite',
            name='declarationModificative',
            field=models.ManyToManyField(blank=True, to='rccm.declaration', verbose_name='Déclaration modificative'),
        ),
    ]
