# Generated by Django 5.1.4 on 2025-04-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0016_declaration_remove_formalite_declarationmodificative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalite',
            name='optionActivite',
        ),
    ]
