# Generated by Django 5.1.4 on 2025-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0017_remove_formalite_optionactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='optionDeclaration',
            field=models.ManyToManyField(blank=True, to='rccm.optiondeclaration', verbose_name='Option'),
        ),
    ]
