# Generated by Django 5.1.4 on 2025-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0018_formalite_optiondeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalite',
            name='declarationModificative',
            field=models.ManyToManyField(to='rccm.declaration', verbose_name='Déclaration modificative'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='optionDeclaration',
            field=models.ManyToManyField(to='rccm.optiondeclaration', verbose_name='Option'),
        ),
    ]
