# Generated by Django 5.1.4 on 2025-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0020_alter_formalite_declarationmodificative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='ancienDenomination',
            field=models.TextField(blank=True, null=True, verbose_name='Ancienne Denomination'),
        ),
    ]
