# Generated by Django 5.1.4 on 2025-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0021_formalite_anciendenomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnephysiqueengager',
            name='statut',
            field=models.TextField(blank=True, choices=[('Nomination', 'Nomination'), ('Revocation', 'Revocation')], null=True, verbose_name='Statut'),
        ),
    ]
