# Generated by Django 5.1.4 on 2025-04-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0022_personnephysiqueengager_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnephysique',
            name='champsRectifier',
            field=models.TextField(blank=True, null=True, verbose_name='Champs rectifier'),
        ),
        migrations.AlterField(
            model_name='personnephysiqueengager',
            name='statut',
            field=models.TextField(blank=True, choices=[('1', 'Personne Nommée'), ('2', 'Personne Révoquée'), ('3', 'Nouvelle Personne Physique')], null=True, verbose_name='Statut'),
        ),
    ]
