# Generated by Django 5.1.4 on 2025-04-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0023_personnephysique_champsrectifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='chef_greffe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formalite_chef_greffe', to=settings.AUTH_USER_MODEL, verbose_name='Chef de Greffe'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formalite_creer_par', to=settings.AUTH_USER_MODEL, verbose_name='Formalité Creer par'),
        ),
    ]
