# Generated by Django 5.1.4 on 2025-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0024_formalite_chef_greffe_alter_formalite_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalite',
            name='formaliteSignee',
        ),
        migrations.AddField(
            model_name='formalite',
            name='statut',
            field=models.TextField(blank=True, default='NON SIGNÉE', null=True, verbose_name='Statut'),
        ),
    ]
