# Generated by Django 5.1.4 on 2025-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0025_remove_formalite_formalitesignee_formalite_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalite',
            name='formaliteSignee',
            field=models.FileField(blank=True, null=True, upload_to='formalite_signees/', verbose_name='Formalité signée'),
        ),
        migrations.AlterField(
            model_name='formalite',
            name='statut',
            field=models.TextField(blank=True, default='NON_SIGNER', null=True, verbose_name='Statut'),
        ),
    ]
