# Generated by Django 5.1.4 on 2025-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0026_formalite_formalitesignee_alter_formalite_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rccm',
            name='typeRccm',
            field=models.TextField(blank=True, choices=[('PERSONNE PHYSIQUE', 'Personne physique'), ('PERSONNE MORALE', 'Personne morale')], null=True, verbose_name='Type Rccm'),
        ),
    ]
