# Generated by Django 5.1.4 on 2025-07-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0027_rccm_typerccm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociesMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.TextField(blank=True, null=True, verbose_name='Activité')),
                ('dateDebut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('nombreSalarierPrevu', models.IntegerField(blank=True, null=True, verbose_name='Nombre de salarié prevu')),
                ('etablissement', models.TextField(blank=True, null=True, verbose_name='Principale etablissement ou succursale')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('origine', models.CharField(blank=True, choices=[('creation', 'création'), ('achat', 'achat'), ('apport', 'apport'), ('prise_en_location_gerance', 'prise en location gérance')], max_length=50, null=True, verbose_name='Origine')),
                ('prenomPrecedentExploitant', models.TextField(blank=True, null=True, verbose_name='Prenom précédent exploitant')),
                ('nomPrecedentExploitant', models.TextField(blank=True, null=True, verbose_name='Nom précédent exploitant')),
                ('banqueApport', models.TextField(blank=True, null=True, verbose_name='Loueur de fonds')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementSecondaireMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=50, null=True, verbose_name='Existance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('activite', models.TextField(blank=True, null=True, verbose_name='Activité')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='GerantMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('fonction', models.TextField(blank=True, null=True, verbose_name='Fonction')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.TextField(blank=True, null=True, verbose_name='Denomination')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('siege', models.TextField(blank=True, null=True, verbose_name='Siège')),
                ('rccmSiege', models.TextField(blank=True, null=True, verbose_name='Siège RCCM')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('formeJuridique', models.TextField(blank=True, null=True, verbose_name='Forme juridique')),
                ('capitalSocial', models.TextField(blank=True, null=True, verbose_name='Capital social')),
                ('dontNumeraires', models.TextField(blank=True, null=True, verbose_name='Dont numeraires')),
                ('dontNature', models.TextField(blank=True, null=True, verbose_name='Dont nature')),
                ('duree', models.IntegerField(blank=True, null=True, verbose_name='Durée (en années)')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
    ]
