# Generated by Django 5.1.4 on 2025-07-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0028_associesmorale_etablissementmorale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissaireComptesMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(blank=True, null=True, verbose_name='Prenom')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='Nom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('lieuNaissance', models.TextField(blank=True, null=True, verbose_name='Lieu naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('fonction', models.TextField(blank=True, null=True, verbose_name='Fonction')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
    ]
