# Generated by Django 5.1.4 on 2025-07-28 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0029_commissairecomptesmorale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiviteAnterieure',
            new_name='ActivitesAnterieuresPersonne',
        ),
        migrations.RenameModel(
            old_name='EtablissementSecondaire',
            new_name='EtablissementSecondairePersonne',
        ),
        migrations.RenameModel(
            old_name='Gerant',
            new_name='GerantPersonne',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='ancienDenomination',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='mandataire',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='nomCommercial',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='siegeSocial',
        ),
        migrations.RemoveField(
            model_name='formalite',
            name='sigle',
        ),
        migrations.RemoveField(
            model_name='rccm',
            name='capital_social',
        ),
        migrations.RemoveField(
            model_name='rccm',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='rccm',
            name='forme_juridique',
        ),
        migrations.RemoveField(
            model_name='rccm',
            name='nom_banque',
        ),
        migrations.RemoveField(
            model_name='rccm',
            name='numero_compte',
        ),
        migrations.CreateModel(
            name='EtablissementPersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCommercial', models.TextField(blank=True, null=True, verbose_name='Nom commercial')),
                ('rccm', models.TextField(blank=True, null=True, verbose_name='N')),
                ('denomination', models.TextField(blank=True, null=True, verbose_name='Denomination')),
                ('ancienDenomination', models.TextField(blank=True, null=True, verbose_name='Ancienne Denomination')),
                ('sigle', models.TextField(blank=True, null=True, verbose_name='Sigle')),
                ('mandataire', models.TextField(blank=True, null=True, verbose_name='Mandataire')),
                ('siegeSocial', models.TextField(blank=True, null=True, verbose_name='Siege Social')),
                ('activites', models.TextField(blank=True, null=True, verbose_name='Activités')),
                ('activitesAjouter', models.TextField(blank=True, null=True, verbose_name='Activités Ajoutées')),
                ('activitesSupprimer', models.TextField(blank=True, null=True, verbose_name='Activités Supprimées')),
                ('activitesActualiser', models.TextField(blank=True, null=True, verbose_name='Activités Actualisées')),
                ('adresseEtablissement', models.TextField(blank=True, null=True, verbose_name='Adresse etablissement')),
                ('ancienneAdresse', models.TextField(blank=True, null=True, verbose_name='Ancienne adresse')),
                ('nouvelleAdresse', models.TextField(blank=True, null=True, verbose_name='Nouvelle adresse')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de creation etablissement')),
                ('formalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rccm.formalite', verbose_name='Formalité')),
            ],
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
    ]
