# Generated by Django 5.1.4 on 2025-07-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0030_rename_activiteanterieure_activitesanterieurespersonne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissementmorale',
            old_name='denomination',
            new_name='activite',
        ),
    ]
