# Generated by Django 5.1.4 on 2025-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccm', '0031_rename_denomination_etablissementmorale_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='typeRccm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
